### ISSUE TITLE
I tried the pose on the itw_videos/reel2, but results seems a little distance from correctness

### ISSUE THREAD

**Issue by xdfeng07** [facebookresearch/sapiens#9] opened 2024-08-26 09:22 UTC
![image](https://github.com/user-attachments/assets/1d2a0e10-d2aa-4788-a70f-367c8a82b6d3)
and the keypoints always seem a little above the correct coordinates
can anybody help???

**Comment by xdfeng07** [comment] 2024-08-26 09:25
I used the script pose_keypoints308.sh

**Comment by rawalkhirodkar** [comment] 2024-08-26 12:55
@xdfeng07 did you make any modifications to the script?

**Comment by xdfeng07** [comment] 2024-08-27 02:32
> @xdfeng07 did you make any modifications to the script?

no, i extracted it from the scripts and run it in a jupyter lab

i will try with the pth version, or the script then

**Comment by xdfeng07** [comment] 2024-08-27 02:34
> @xdfeng07 did you make any modifications to the script?

maybe i get where the problem is, i just ignore the "pip install -e " with the cv and pretrain directories, so I am using the pypi version of the mm--- works. I will reinstall and try

**Comment by rawalkhirodkar** [comment] 2024-08-27 02:39
@xdfeng07 I am unable to reproduce this error.
For inference using torchscript models (pose_keypoint308.sh), only mmdet is a dependency. You can also skip the bounding box detection by removing the detection arguments, in that case entire image is taken as input.

Let me know if this works with reinstalls.

**Comment by xdfeng07** [comment] 2024-08-27 02:53
> @xdfeng07 I am unable to reproduce this error. For inference using torchscript models (pose_keypoint308.sh), only mmdet is a dependency. You can also skip the bounding box detection by removing the detection arguments, in that case entire image is taken as input.
> 
> Let me know if this works with reinstalls.

ok, i will give another try, many thanks!

**Comment by rawalkhirodkar** [comment] 2024-08-27 03:55
@xdfeng07 closing the issue for now. please re-open the issue if problem persists.

**Closed by rawalkhirodkar** 2024-08-27 03:55 UTC
